name: validate

on:
  push:
  pull_request:

jobs:
  static:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Validate repository docs
        shell: pwsh
        run: ./tests/static/validate.ps1
